/// Flutter icons AbilIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AbilIcon
///      fonts:
///       - asset: fonts/AbilIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class AbilIcon {
  AbilIcon._();

  static const _kFontFam = 'AbilIcon';
  static const String? _kFontPkg = null;

  static const IconData produk = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menejemen = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keuangan = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barang = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kategori = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stok = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_queue = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
